/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Game_Board */

#ifndef _Included_Game_Board
#define _Included_Game_Board
#ifdef __cplusplus
extern "C" {
#endif
#undef Game_Board_FOCUS_TRAVERSABLE_UNKNOWN
#define Game_Board_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef Game_Board_FOCUS_TRAVERSABLE_DEFAULT
#define Game_Board_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef Game_Board_FOCUS_TRAVERSABLE_SET
#define Game_Board_FOCUS_TRAVERSABLE_SET 2L
#undef Game_Board_TOP_ALIGNMENT
#define Game_Board_TOP_ALIGNMENT 0.0f
#undef Game_Board_CENTER_ALIGNMENT
#define Game_Board_CENTER_ALIGNMENT 0.5f
#undef Game_Board_BOTTOM_ALIGNMENT
#define Game_Board_BOTTOM_ALIGNMENT 1.0f
#undef Game_Board_LEFT_ALIGNMENT
#define Game_Board_LEFT_ALIGNMENT 0.0f
#undef Game_Board_RIGHT_ALIGNMENT
#define Game_Board_RIGHT_ALIGNMENT 1.0f
#undef Game_Board_serialVersionUID
#define Game_Board_serialVersionUID -7644114512714619750i64
#undef Game_Board_serialVersionUID
#define Game_Board_serialVersionUID 4613797578919906343i64
#undef Game_Board_INCLUDE_SELF
#define Game_Board_INCLUDE_SELF 1L
#undef Game_Board_SEARCH_HEAVYWEIGHTS
#define Game_Board_SEARCH_HEAVYWEIGHTS 1L
#undef Game_Board_NOT_OBSCURED
#define Game_Board_NOT_OBSCURED 0L
#undef Game_Board_PARTIALLY_OBSCURED
#define Game_Board_PARTIALLY_OBSCURED 1L
#undef Game_Board_COMPLETELY_OBSCURED
#define Game_Board_COMPLETELY_OBSCURED 2L
#undef Game_Board_WHEN_FOCUSED
#define Game_Board_WHEN_FOCUSED 0L
#undef Game_Board_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define Game_Board_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef Game_Board_WHEN_IN_FOCUSED_WINDOW
#define Game_Board_WHEN_IN_FOCUSED_WINDOW 2L
#undef Game_Board_UNDEFINED_CONDITION
#define Game_Board_UNDEFINED_CONDITION -1L
#undef Game_Board_IS_DOUBLE_BUFFERED
#define Game_Board_IS_DOUBLE_BUFFERED 0L
#undef Game_Board_ANCESTOR_USING_BUFFER
#define Game_Board_ANCESTOR_USING_BUFFER 1L
#undef Game_Board_IS_PAINTING_TILE
#define Game_Board_IS_PAINTING_TILE 2L
#undef Game_Board_IS_OPAQUE
#define Game_Board_IS_OPAQUE 3L
#undef Game_Board_KEY_EVENTS_ENABLED
#define Game_Board_KEY_EVENTS_ENABLED 4L
#undef Game_Board_FOCUS_INPUTMAP_CREATED
#define Game_Board_FOCUS_INPUTMAP_CREATED 5L
#undef Game_Board_ANCESTOR_INPUTMAP_CREATED
#define Game_Board_ANCESTOR_INPUTMAP_CREATED 6L
#undef Game_Board_WIF_INPUTMAP_CREATED
#define Game_Board_WIF_INPUTMAP_CREATED 7L
#undef Game_Board_ACTIONMAP_CREATED
#define Game_Board_ACTIONMAP_CREATED 8L
#undef Game_Board_CREATED_DOUBLE_BUFFER
#define Game_Board_CREATED_DOUBLE_BUFFER 9L
#undef Game_Board_IS_PRINTING
#define Game_Board_IS_PRINTING 11L
#undef Game_Board_IS_PRINTING_ALL
#define Game_Board_IS_PRINTING_ALL 12L
#undef Game_Board_IS_REPAINTING
#define Game_Board_IS_REPAINTING 13L
#undef Game_Board_WRITE_OBJ_COUNTER_FIRST
#define Game_Board_WRITE_OBJ_COUNTER_FIRST 14L
#undef Game_Board_RESERVED_1
#define Game_Board_RESERVED_1 15L
#undef Game_Board_RESERVED_2
#define Game_Board_RESERVED_2 16L
#undef Game_Board_RESERVED_3
#define Game_Board_RESERVED_3 17L
#undef Game_Board_RESERVED_4
#define Game_Board_RESERVED_4 18L
#undef Game_Board_RESERVED_5
#define Game_Board_RESERVED_5 19L
#undef Game_Board_RESERVED_6
#define Game_Board_RESERVED_6 20L
#undef Game_Board_WRITE_OBJ_COUNTER_LAST
#define Game_Board_WRITE_OBJ_COUNTER_LAST 21L
#undef Game_Board_REQUEST_FOCUS_DISABLED
#define Game_Board_REQUEST_FOCUS_DISABLED 22L
#undef Game_Board_INHERITS_POPUP_MENU
#define Game_Board_INHERITS_POPUP_MENU 23L
#undef Game_Board_OPAQUE_SET
#define Game_Board_OPAQUE_SET 24L
#undef Game_Board_AUTOSCROLLS_SET
#define Game_Board_AUTOSCROLLS_SET 25L
#undef Game_Board_FOCUS_TRAVERSAL_KEYS_FORWARD_SET
#define Game_Board_FOCUS_TRAVERSAL_KEYS_FORWARD_SET 26L
#undef Game_Board_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET
#define Game_Board_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET 27L
/*
 * Class:     Game_Board
 * Method:    resetParameters
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Game_Board_resetParameters
  (JNIEnv *, jobject);

/*
 * Class:     Game_Board
 * Method:    getBoardWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_Board_getBoardWidth
  (JNIEnv *, jobject);

/*
 * Class:     Game_Board
 * Method:    getBoardHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_Board_getBoardHeight
  (JNIEnv *, jobject);

/*
 * Class:     Game_Board
 * Method:    getBoardCellState
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Game_Board_getBoardCellState
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Game_Board
 * Method:    movePiece
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_Game_Board_movePiece
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Game_Board
 * Method:    isGameOver
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Game_Board_isGameOver
  (JNIEnv *, jobject);

/*
 * Class:     Game_Board
 * Method:    getCurrentPlayer
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_Game_Board_getCurrentPlayer
  (JNIEnv *, jobject);

/*
 * Class:     Game_Board
 * Method:    setCurrentPiece
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_Game_Board_setCurrentPiece
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Game_Board
 * Method:    getWinner
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Game_Board_getWinner
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
